import Link from "next/link";

export const metadata = {
  title: "Terms of Service · Debate Master",
  description: "Terms and conditions governing the use of the Debate Master platform.",
};

export default function TermsOfServicePage() {
  const lastUpdated = "September 2, 2026";

  return (
    <div className="mx-auto max-w-4xl px-4 py-12 sm:px-6 lg:px-8">
      <div className="border-b border-stage-border pb-8">
        <Link
          href="/"
          className="inline-flex items-center text-xs font-medium text-stage-accent hover:underline mb-4"
        >
          ← Back to Debate Master
        </Link>
        <h1 className="text-3xl font-extrabold tracking-tight text-stage-text sm:text-4xl">
          Terms of Service
        </h1>
        <p className="mt-2 text-sm text-stage-muted">
          Last updated: {lastUpdated}
        </p>
      </div>

      <div className="mt-8 space-y-10 text-sm leading-relaxed text-stage-muted">
        <section className="space-y-3">
          <h2 className="text-lg font-bold text-stage-text">1. Agreement to Terms</h2>
          <p>
            These Terms of Service (&ldquo;Terms&rdquo;) constitute a legally binding agreement between you and
            Debate Master (&ldquo;we,&rdquo; &ldquo;our,&rdquo; or &ldquo;us&rdquo;) concerning your access to and
            use of our website, mobile application, and interactive debate services (the &ldquo;Service&rdquo;).
          </p>
          <p>
            By accessing or using the Service, you agree to be bound by these Terms. If you do not agree, you must
            discontinue use of the Service immediately.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-lg font-bold text-stage-text">2. Nature of Service & AI Simulation Disclaimer</h2>
          <p>
            Debate Master is an interactive educational and skill-building platform designed to help users sharpen
            their rhetorical, analytical, and argumentation abilities against simulated artificial intelligence opponents.
          </p>
          <ul className="list-disc pl-5 space-y-2">
            <li>
              <strong className="text-stage-text">Fictional Intellectual Archetypes:</strong> All built-in AI debaters
              (such as The Consequentialist, The Logician, The Contrarian, The Presuppositionalist, The Traditionalist,
              and The Voluntaryist) are original fictional archetypes created for rhetorical practice. They do not represent,
              and are not affiliated with or endorsed by, any real living individual or public figure.
            </li>
            <li>
              <strong className="text-stage-text">Not Professional Advice:</strong> Arguments, responses, scores, and
              coaching evaluations generated by AI models are for educational and entertainment simulation only. They do
              not constitute legal, medical, financial, or political advice.
            </li>
          </ul>
        </section>

        <section className="space-y-3">
          <h2 className="text-lg font-bold text-stage-text">3. User Accounts & Registration</h2>
          <p>
            To access certain features, you must create an account. You are responsible for maintaining the confidentiality
            of your account credentials and for all activities conducted under your account. You agree to provide accurate
            and complete information during registration.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-lg font-bold text-stage-text">4. Subscriptions, Billing & Cancellations</h2>
          <ul className="list-disc pl-5 space-y-2">
            <li>
              <strong className="text-stage-text">Free Tier:</strong> Free accounts receive access to a monthly debate
              allowance and standard coaching overviews.
            </li>
            <li>
              <strong className="text-stage-text">Premium Subscriptions:</strong> Premium access provides unlimited debates,
              neural voice synthesis (ElevenLabs), in-depth 4-dimension rubric scoring, and practice generators. Pricing
              is billed in advance on a recurring monthly or annual basis as displayed at checkout.
            </li>
            <li>
              <strong className="text-stage-text">Cancellation:</strong> You may cancel your subscription at any time
              through your account billing portal. Cancellation takes effect at the end of the current billing cycle, and
              you will maintain access until that date.
            </li>
            <li>
              <strong className="text-stage-text">Payment Processing:</strong> Payments are processed through Stripe. By
              subscribing, you agree to Stripe&apos;s applicable terms and authorize recurring charges until canceled.
            </li>
          </ul>
        </section>

        <section className="space-y-3">
          <h2 className="text-lg font-bold text-stage-text">5. Acceptable Use & Prohibited Conduct</h2>
          <p>You agree not to use the Service to:</p>
          <ul className="list-disc pl-5 space-y-2">
            <li>Submit hate speech, slurs, threats of violence, sexually explicit content, or targeted harassment.</li>
            <li>Attempt to jailbreak, exploit, or bypass safety guardrails of the underlying artificial intelligence models.</li>
            <li>Engage in automated scraping, reverse-engineering, or denial-of-service attacks against our infrastructure.</li>
            <li>Impersonate any person or entity or misrepresent affiliations.</li>
          </ul>
        </section>

        <section className="space-y-3">
          <h2 className="text-lg font-bold text-stage-text">6. Intellectual Property Rights</h2>
          <p>
            You retain ownership of the original text arguments and speeches you compose and submit on the platform.
            Debate Master and its licensors retain all rights, title, and interest in and to the platform software,
            UI design, AI persona archetypes, logos, trademarks, and proprietary evaluation algorithms.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-lg font-bold text-stage-text">7. Disclaimer of Warranties & Limitation of Liability</h2>
          <p>
            THE SERVICE IS PROVIDED ON AN &ldquo;AS IS&rdquo; AND &ldquo;AS AVAILABLE&rdquo; BASIS WITHOUT WARRANTIES
            OF ANY KIND, EITHER EXPRESS OR IMPLIED. TO THE MAXIMUM EXTENT PERMITTED BY LAW, DEBATE MASTER DISCLAIMS
            ALL WARRANTIES, INCLUDING MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT.
          </p>
          <p>
            IN NO EVENT SHALL DEBATE MASTER BE LIABLE FOR INDIRECT, INCIDENTAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES
            ARISING OUT OF YOUR ACCESS TO OR USE OF THE SERVICE.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-lg font-bold text-stage-text">8. Changes to Terms</h2>
          <p>
            We reserve the right to modify these Terms at any time. Material changes will be indicated by updating the
            &ldquo;Last updated&rdquo; date at the top of this document. Continued use of the Service after modifications
            signifies your acceptance.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-lg font-bold text-stage-text">9. Contact Us</h2>
          <p>
            For questions regarding these Terms of Service, please contact us at:
          </p>
          <p className="font-mono text-xs text-stage-text bg-stage-surface p-3 rounded-lg border border-stage-border inline-block">
            support@debatemaster.app
          </p>
        </section>
      </div>
    </div>
  );
}
